using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace SignalStack.Worker.Jobs.EodSignalRunner;

/// <summary>
/// Entry signal record persisted to the MongoDB <c>entry_signals</c> collection.
/// Generated by the EOD Signal Runner (EODSR) for next-trading-day entry signals.
///
/// REQ-STRAT-015/015a: combined signal record per (user, symbol, session).
/// REQ-STRAT-028: provenance fields never mutate after creation.
/// </summary>
public sealed class EntrySignalDocument
{
    [BsonId]
    public ObjectId Id { get; init; }

    /// <summary>Platform user ID who owns this signal.</summary>
    [BsonElement("user_id")]
    public required string UserId { get; init; }

    /// <summary>NSE trading symbol that qualified.</summary>
    [BsonElement("symbol")]
    public required string Symbol { get; init; }

    /// <summary>Trading session date for which this entry signal was generated (yyyy-MM-dd).</summary>
    [BsonElement("session_date")]
    public required string SessionDate { get; init; }

    /// <summary>Signal type identifiers that contributed (REQ-STRAT-015a combined signal).</summary>
    [BsonElement("signal_type_ids")]
    public required List<string> SignalTypeIds { get; init; }

    /// <summary>Human-readable names of contributing Signal types (REQ-STRAT-015a).</summary>
    [BsonElement("signal_type_names")]
    public required List<string> SignalTypeNames { get; init; }

    /// <summary>
    /// Provenance: map of Signal Subscription ID → version_id that was active at EODSR run time.
    /// Never mutated after creation. REQ-STRAT-028(a).
    /// </summary>
    [BsonElement("signal_subscription_version_ids")]
    public required Dictionary<string, string> SignalSubscriptionVersionIds { get; init; }

    /// <summary>
    /// Provenance: map of Signal type ID → code_version at EODSR run time.
    /// Never mutated after creation. REQ-STRAT-028(b).
    /// </summary>
    [BsonElement("signal_code_versions")]
    public required Dictionary<string, string> SignalCodeVersions { get; init; }

    /// <summary>ID of the Signal Subscription with highest user-defined priority (REQ-STRAT-015b).</summary>
    [BsonElement("primary_subscription_id")]
    public required string PrimarySubscriptionId { get; init; }

    /// <summary>EODSR job run ID that generated this entry signal.</summary>
    [BsonElement("job_run_id")]
    public required string JobRunId { get; init; }

    /// <summary>UTC timestamp when the signal was generated.</summary>
    [BsonElement("generated_at")]
    public required DateTime GeneratedAt { get; init; }

    /// <summary>Signal-type-specific payload (candidate entry price, indicators, etc.).</summary>
    [BsonElement("signal_data")]
    [BsonIgnoreIfNull]
    public BsonDocument? SignalData { get; init; }
}
