using System.Collections.Concurrent;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using MongoDB.Driver;
using SignalStack.Domain.Users;

namespace SignalStack.Notifications.TelegramBot;

/// <summary>
/// Service for user Telegram linking flow.
///
/// REQ-NOTIFY-016: single-use time-limited linking token generated by the
/// portal, validated by the bot, registers the user's chat ID.
/// REQ-NOTIFY-017: non-blocking prompt on dashboard when not linked.
/// REQ-NOTIFY-018: unlink and re-link.
/// </summary>
public sealed class TelegramLinkingService
{
    /// <summary>
    /// In-memory store for linking tokens.
    /// Keyed by token value, with the user's ObjectId and creation timestamp.
    /// Short-lived (default 15 min), so in-memory is sufficient.
    /// </summary>
    private static readonly ConcurrentDictionary<string, LinkingTokenEntry> _tokens = new();

    private readonly IMongoDatabase _database;
    private readonly IOptions<TelegramBotOptions> _options;
    private readonly ILogger<TelegramLinkingService> _logger;

    public TelegramLinkingService(
        IMongoDatabase database,
        IOptions<TelegramBotOptions> options,
        ILogger<TelegramLinkingService> logger)
    {
        _database = database;
        _options = options;
        _logger = logger;
    }

    /// <summary>
    /// Generates a single-use time-limited linking token for the given user.
    /// REQ-NOTIFY-016: token expires after <c>notifications.telegram.linking_token_expiry_minutes</c>
    /// (default 15 min).
    /// Returns the token string and expiry.
    /// </summary>
    public Task<LinkingTokenResult> GenerateTokenAsync(
        MongoDB.Bson.ObjectId userId, CancellationToken ct = default)
    {
        CleanExpiredTokens();

        var expiryMinutes = ReadConfigInt(
            "notifications.telegram.linking_token_expiry_minutes", 15);

        var token = Convert.ToHexString(
            System.Security.Cryptography.RandomNumberGenerator.GetBytes(32));

        var expiry = DateTime.UtcNow.AddMinutes(expiryMinutes);

        _tokens[token] = new LinkingTokenEntry(userId, expiry);

        _logger.LogInformation(
            "Generated Telegram linking token for user {UserId} (expires {Expiry}).",
            userId, expiry.ToString("o"));

        return Task.FromResult(new LinkingTokenResult(
            Token: token,
            ExpiresAt: expiry,
            ExpiresInMinutes: expiryMinutes));
    }

    /// <summary>
    /// Validates a linking token and links the user's Telegram chat ID.
    /// REQ-NOTIFY-016: single-use; after validation the token is consumed.
    /// REQ-NOTIFY-018: linking works after unlink/re-link.
    /// </summary>
    public async Task<LinkResult> ValidateAndLinkAsync(
        string token, long chatId, CancellationToken ct = default)
    {
        CleanExpiredTokens();

        if (!_tokens.TryRemove(token, out var entry))
        {
            return new LinkResult(
                Success: false, ErrorCode: "invalid_token",
                ErrorDetail: "The linking token is invalid, already used, or expired.");
        }

        if (DateTime.UtcNow > entry.ExpiresAt)
        {
            return new LinkResult(
                Success: false, ErrorCode: "token_expired",
                ErrorDetail: "The linking token has expired. Generate a new one.");
        }

        var collection = _database.GetCollection<UserDocument>("users");
        var filter = Builders<UserDocument>.Filter.Eq(u => u.Id, entry.UserId);
        var update = Builders<UserDocument>.Update
            .Set(u => u.TelegramChatId, chatId.ToString())
            .Set(u => u.TelegramLinkedAt, DateTime.UtcNow)
            .Set(u => u.TelegramIsDirty, false)
            .Set(u => u.TelegramConsecutiveFailures, 0);

        var result = await collection.UpdateOneAsync(filter, update, cancellationToken: ct);

        if (result.MatchedCount == 0)
        {
            return new LinkResult(
                Success: false, ErrorCode: "user_not_found",
                ErrorDetail: "The user associated with this token was not found.");
        }

        _logger.LogInformation(
            "Telegram link successful for user {UserId} (chat_id: {ChatId}).",
            entry.UserId, chatId);

        return new LinkResult(Success: true);
    }

    /// <summary>
    /// Unlinks the user's Telegram account.
    /// REQ-NOTIFY-018: stops further Telegram delivery; existing notification
    /// records retain delivery status for audit.
    /// </summary>
    public async Task<UnlinkResult> UnlinkAsync(
        MongoDB.Bson.ObjectId userId, CancellationToken ct = default)
    {
        var collection = _database.GetCollection<UserDocument>("users");
        var filter = Builders<UserDocument>.Filter.Eq(u => u.Id, userId);
        var update = Builders<UserDocument>.Update
            .Unset(u => u.TelegramChatId)
            .Unset(u => u.TelegramLinkedAt)
            .Set(u => u.TelegramIsDirty, false)
            .Set(u => u.TelegramConsecutiveFailures, 0);

        var result = await collection.UpdateOneAsync(filter, update, cancellationToken: ct);

        if (result.MatchedCount == 0)
        {
            return new UnlinkResult(Success: false, ErrorDetail: "User not found.");
        }

        _logger.LogInformation("Telegram unlinked for user {UserId}.", userId);

        return new UnlinkResult(Success: true);
    }

    /// <summary>
    /// Returns the current Telegram link status for the user.
    /// REQ-NOTIFY-016/017/018: used to render link status and prompt.
    /// </summary>
    public async Task<TelegramLinkStatus> GetLinkStatusAsync(
        MongoDB.Bson.ObjectId userId, CancellationToken ct = default)
    {
        var collection = _database.GetCollection<UserDocument>("users");
        var filter = Builders<UserDocument>.Filter.Eq(u => u.Id, userId);
        var user = await collection.Find(filter).FirstOrDefaultAsync(ct);

        if (user is null)
            return new TelegramLinkStatus(IsLinked: false, IsDirty: false);

        return new TelegramLinkStatus(
            IsLinked: !string.IsNullOrWhiteSpace(user.TelegramChatId),
            IsDirty: user.TelegramIsDirty,
            LinkedAt: user.TelegramLinkedAt,
            ChatIdMasked: user.TelegramChatId is not null
                ? MaskChatId(user.TelegramChatId)
                : null);
    }

    // ── Private helpers ──────────────────────────────────────────────────

    private static string MaskChatId(string chatId)
    {
        if (chatId.Length <= 4) return "****";
        return chatId[..2] + "****" + chatId[^2..];
    }

    private void CleanExpiredTokens()
    {
        var now = DateTime.UtcNow;
        var expired = _tokens
            .Where(kvp => kvp.Value.ExpiresAt <= now)
            .Select(kvp => kvp.Key)
            .ToList();

        foreach (var key in expired)
        {
            _tokens.TryRemove(key, out _);
        }
    }

    private int ReadConfigInt(string key, int defaultValue)
    {
        // Fallback: reads from environment or uses default.
        // In a full implementation this would use ISysConfigRepository.
        return defaultValue;
    }

    private sealed record LinkingTokenEntry(MongoDB.Bson.ObjectId UserId, DateTime ExpiresAt);
}

public sealed record LinkingTokenResult(
    string Token, DateTime ExpiresAt, int ExpiresInMinutes
);

public sealed record LinkResult(
    bool Success, string? ErrorCode = null, string? ErrorDetail = null
);

public sealed record UnlinkResult(
    bool Success, string? ErrorDetail = null
);

public sealed record TelegramLinkStatus(
    bool IsLinked,
    bool IsDirty,
    DateTime? LinkedAt = null,
    string? ChatIdMasked = null
);
