using System.Diagnostics;
using System.Diagnostics.Metrics;

namespace SignalStack.Worker.Observability;

internal static class WorkerTelemetry
{
  public const string ServiceName = "SignalStack.Worker";

  public static readonly ActivitySource ActivitySource = new(ServiceName);
  public static readonly Meter Meter = new(ServiceName);

  // ── Heartbeat / singleton lease ───────────────────────────────────────

  public static readonly Counter<long> HeartbeatCounter = Meter.CreateCounter<long>("worker.heartbeat.count");
  public static readonly Histogram<double> LeaseRefreshDurationMilliseconds = Meter.CreateHistogram<double>("worker.singleton.lease_refresh.duration_ms");

  // ── Order callback reliability counters (P7-T10 / REQ-ORDER-015d) ─────

  public static readonly Counter<long> OrderReconciledViaLadsOnlyTotal = Meter.CreateCounter<long>(
      "order_reconciled_via_lads_only_total",
      description: "Count of intents reconciled by LADS without a callback (callback-missed path).");

  public static readonly Counter<long> OrderUnresolvedTotal = Meter.CreateCounter<long>(
      "order_unresolved_total",
      description: "Count of intents that timed out unresolved without a matching FYERS order.");

  public static readonly Counter<long> OrderOrphanTotal = Meter.CreateCounter<long>(
      "order_orphan_total",
      description: "Count of orphan FYERS trades with no matching platform intent.");

  // ── DataSync (DS) metrics ─────────────────────────────────────────────

  public static readonly Histogram<double> DataSyncCycleDurationMs = Meter.CreateHistogram<double>(
      "datasync.cycle.duration_ms", unit: "ms",
      description: "Duration of a DataSync cycle (one poll iteration).");

  public static readonly Counter<long> DataSyncSymbolsProcessedTotal = Meter.CreateCounter<long>(
      "datasync.symbols_processed.total",
      description: "Symbols processed per DataSync session.");

  public static readonly Counter<long> DataSyncOutcomeTotal = Meter.CreateCounter<long>(
      "datasync.session.outcome.total",
      description: "DataSync session outcomes by result.");

  // ── HistoricDataSeed (HDS) metrics ────────────────────────────────────

  public static readonly Histogram<double> HdsSeedDurationMs = Meter.CreateHistogram<double>(
      "hds.seed.duration_ms", unit: "ms",
      description: "Duration of per-symbol HDS seeding operation.");

  public static readonly Counter<long> HdsSymbolsSeededTotal = Meter.CreateCounter<long>(
      "hds.symbols_seeded.total",
      description: "Symbols seeded by HDS.");

  // ── EOD Signal Runner (EODSR) metrics ─────────────────────────────────

  public static readonly Histogram<double> EodSignalRunDurationMs = Meter.CreateHistogram<double>(
      "eodsr.run.duration_ms", unit: "ms",
      description: "Duration of an EODSR evaluation run.");

  public static readonly Counter<long> EodSignalSignalsGeneratedTotal = Meter.CreateCounter<long>(
      "eodsr.signals_generated.total",
      description: "Entry signals generated by EODSR.");

  // ── Live Account Data Sync (LADS) metrics ─────────────────────────────

  public static readonly Histogram<double> LadsSyncDurationMs = Meter.CreateHistogram<double>(
      "lads.sync.duration_ms", unit: "ms",
      description: "Per-user LADS sync duration.");

  // ── Notification Delivery (NDJ) metrics ───────────────────────────────

  public static readonly Histogram<double> NdjDeliveryDurationMs = Meter.CreateHistogram<double>(
      "ndj.delivery.duration_ms", unit: "ms",
      description: "Notification delivery processing time.");

  public static readonly Counter<long> NdjDeliveredTotal = Meter.CreateCounter<long>(
      "ndj.delivered.total",
      description: "Notifications delivered by type.");

  // ── Admin FYERS token check metrics ───────────────────────────────────

  public static readonly Counter<long> FyersTokenCheckOutcomeTotal = Meter.CreateCounter<long>(
      "fyers_token_check.outcome.total",
      description: "Admin FYERS token check outcomes by result.");

  // ── Live Market Scan (LMDS) metrics ───────────────────────────────────

  public static readonly Histogram<double> LmdsScanDurationMs = Meter.CreateHistogram<double>(
      "lmds.scan.duration_ms", unit: "ms",
      description: "LMDS scan cycle duration.");

  public static readonly Counter<long> LmdsPositionsScannedTotal = Meter.CreateCounter<long>(
      "lmds.positions_scanned.total",
      description: "Positions evaluated per LMDS scan.");
}
