namespace SignalStack.Api.Backtesting;

/// <summary>Input parameters for a backtest run. REQ-STRAT-009/010/018.</summary>
public sealed record BacktestOptions
{
    public required string SignalTypeId { get; init; }
    public string? SignalSubscriptionVersionId { get; init; }
    public required string Timeframe { get; init; }
    public decimal Slippage { get; init; } = 0.001m;
    public decimal CommissionPct { get; init; } = 0.0001m;
    public required DateOnly DateRangeStart { get; init; }
    public required DateOnly DateRangeEnd { get; init; }
    public decimal StartingEquity { get; init; } = 1_000_000m;
    public string? RmeConfigurationJson { get; init; }
    public string? SignalParametersJson { get; init; }
}

/// <summary>Complete output of a backtest run. REQ-BTSTORE-003/006.</summary>
public sealed record BacktestRunResult
{
    public required Guid RunId { get; init; }
    public required string SignalType { get; init; }
    public string? SignalSubscriptionVersionId { get; init; }
    public required string Timeframe { get; init; }
    public decimal Slippage { get; init; }
    public decimal CommissionPct { get; init; }
    public required DateOnly DateRangeStart { get; init; }
    public required DateOnly DateRangeEnd { get; init; }
    public decimal StartingEquity { get; init; }
    public decimal EndingEquity { get; init; }
    public DateTime RunTimestamp { get; init; }

    // Per-trade data (REQ-BTSTORE-004)
    public required List<BacktestTrade> Trades { get; init; }

    // Position lifecycle events (REQ-BTSTORE-005)
    public required List<BacktestPositionEvent> PositionEvents { get; init; }

    // Equity curve (REQ-BTSTORE-006)
    public required List<EquityPoint> EquityCurve { get; init; }

    // ── Portfolio-level metrics ────────────────────────────────────────────
    public int TotalTrades { get; init; }
    public int WinningTrades { get; init; }
    public int LosingTrades { get; init; }
    public decimal WinRatePct { get; init; }
    public decimal AverageR { get; init; }
    public decimal ExpectancyInR { get; init; }
    public decimal ProfitFactor { get; init; }
    public decimal MaxDrawdownPct { get; init; }
    public decimal MaxDrawdownInR { get; init; }
    public decimal SharpeRatio { get; init; }
    public decimal SortinoRatio { get; init; }
    public decimal RecoveryFactor { get; init; }
    public decimal TotalReturnPct { get; init; }
    public decimal TotalReturnAbsolute { get; init; }

    // Universe coverage and confidence
    public int SkippedSessions { get; init; }
    public int TotalSessions { get; init; }
    public bool LowConfidence { get; init; }
    public decimal UniverseCoveragePct { get; init; }

    // Survivorship bias adjustment — REQ-STRAT-011b
    public decimal RawExpectancy { get; init; }
    public decimal? AdjustedExpectancy { get; init; }
    public decimal SurvivorshipBiasDiscountPct { get; init; }
}

/// <summary>A single trade generated by the backtest. REQ-BTSTORE-004.</summary>
public sealed record BacktestTrade
{
    public required string Symbol { get; init; }
    public required DateOnly EntryDate { get; init; }
    public DateOnly? ExitDate { get; init; }
    public decimal EntryPrice { get; init; }
    public decimal? ExitPrice { get; init; }
    public decimal StopAtEntry { get; init; }
    public string? ExitReason { get; init; }
    public decimal RMultiple { get; init; }
    public decimal GrossPnL { get; init; }
    public decimal NetPnL { get; init; }
    public int Quantity { get; init; }
}

/// <summary>A lifecycle event for a backtest position. REQ-BTSTORE-005.</summary>
public sealed record BacktestPositionEvent
{
    public required string Symbol { get; init; }
    public required DateOnly EventDate { get; init; }
    public required string EventType { get; init; } // add | reduce | close
    public string? RmeState { get; init; }
    public decimal? PeakRMultiple { get; init; }
}

/// <summary>A point on the equity curve. REQ-BTSTORE-006.</summary>
public sealed record EquityPoint
{
    public required DateOnly Date { get; init; }
    public decimal Equity { get; init; }
}

/// <summary>Signal evaluation result for a single candle.</summary>
public sealed record SignalResult
{
    public required DateOnly Date { get; init; }
    public SignalAction Action { get; init; } = SignalAction.None;
    public decimal? EntryPrice { get; init; }
    public decimal? ExitPrice { get; init; }
    public decimal? StopPrice { get; init; }
    public decimal? Atr { get; init; }
    public string? Description { get; init; }
}

public enum SignalAction { None, Entry, Exit }
