using System.Text;
using System.Text.Json;
using Microsoft.Extensions.Options;
using StackExchange.Redis;

namespace SignalStack.Api.Push;

/// <summary>
/// Background service that subscribes to the Redis <c>push:events</c> channel
/// and fans out push events to connected WebSocket clients.
///
/// REQ-NFR-013: Redis is the fan-out layer so push events generated by background
/// workers reach all connected portal instances.
///
/// REQ-DATA-006a(c)(i): when Redis is unreachable, the subscription silently
/// degrades; WebSocket clients that are connected but not receiving events must
/// surface a degradation banner and fall back to polling.
/// </summary>
internal sealed class PushFanOutService : BackgroundService
{
    private readonly PushConnectionManager _connectionManager;
    private readonly IConfiguration _configuration;
    private readonly ILogger<PushFanOutService> _logger;
    private readonly JsonSerializerOptions _jsonOptions;

    private const string PushChannel = "push:events";

    public PushFanOutService(
        PushConnectionManager connectionManager,
        IConfiguration configuration,
        ILogger<PushFanOutService> logger)
    {
        _connectionManager = connectionManager;
        _configuration = configuration;
        _logger = logger;

        _jsonOptions = new JsonSerializerOptions
        {
            PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower,
            WriteIndented = false
        };
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        var connectionString = _configuration.GetConnectionString("Redis")
            ?? _configuration["Redis:ConnectionString"];

        if (string.IsNullOrWhiteSpace(connectionString))
        {
            _logger.LogWarning(
                "Redis connection string is not configured. Push fan-out service will not start. " +
                "REQ-DATA-006a(c)(i): connected clients must fall back to polling.");
            // Keep the service running but idle — Redis may become available later
            // if the connection string is added via config refresh.
            await Task.Delay(Timeout.Infinite, stoppingToken);
            return;
        }

        while (!stoppingToken.IsCancellationRequested)
        {
            try
            {
                await SubscribeAndFanOutAsync(connectionString, stoppingToken);
            }
            catch (OperationCanceledException) when (stoppingToken.IsCancellationRequested)
            {
                break;
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex,
                    "Push fan-out subscription failed. " +
                    "REQ-DATA-006a(c)(i): clients must fall back to polling. " +
                    "Retrying in 30 seconds.");

                try
                {
                    await Task.Delay(TimeSpan.FromSeconds(30), stoppingToken);
                }
                catch (OperationCanceledException)
                {
                    break;
                }
            }
        }
    }

    private async Task SubscribeAndFanOutAsync(string connectionString, CancellationToken ct)
    {
        using var multiplexer = await ConnectionMultiplexer.ConnectAsync(connectionString);
        var subscriber = multiplexer.GetSubscriber();

        _logger.LogInformation(
            "Push fan-out service subscribed to Redis channel {Channel}.",
            PushChannel);

        var channel = new RedisChannel(PushChannel, RedisChannel.PatternMode.Literal);

        await subscriber.SubscribeAsync(channel, async (redisChannel, redisValue) =>
        {
            try
            {
                var json = redisValue.HasValue ? redisValue.ToString() : null;
                if (string.IsNullOrWhiteSpace(json))
                    return;

                var pushEvent = JsonSerializer.Deserialize<PushEvent>(json, _jsonOptions);
                if (pushEvent is null || string.IsNullOrWhiteSpace(pushEvent.UserId))
                    return;

                await _connectionManager.FanOutAsync(pushEvent.UserId, pushEvent, _jsonOptions);
            }
            catch (JsonException ex)
            {
                _logger.LogWarning(ex, "Failed to deserialize push event from Redis.");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error processing push event from Redis.");
            }
        });

        // Keep running until cancellation.
        try
        {
            await Task.Delay(Timeout.Infinite, ct);
        }
        catch (OperationCanceledException)
        {
            // Graceful shutdown.
        }

        try
        {
            await subscriber.UnsubscribeAsync(channel);
        }
        catch
        {
            // Best-effort unsubscribe.
        }

        _logger.LogInformation("Push fan-out service unsubscribed from Redis channel {Channel}.", PushChannel);
    }
}
