namespace SignalStack.Worker.Push;

/// <summary>
/// Publishes push events for real-time delivery to connected portal clients.
///
/// REQ-NFR-013: push events generated by background workers reach all connected
/// portal instances via Redis pub/sub.
///
/// REQ-DATA-006a(c)(i): when Redis is unreachable, the implementation must log
/// a warning and fall through — the event has already been persisted to MongoDB
/// by the caller.
/// </summary>
public interface IPushEventPublisher
{
    /// <summary>
    /// Publishes a push event. On Redis failure, logs a warning and returns false.
    /// The caller is responsible for ensuring the event is durably stored in
    /// MongoDB before calling this method (REQ-DATA-006a(c)(i)).
    /// </summary>
    Task<bool> PublishAsync(
        string eventType,
        string userId,
        string? symbol = null,
        string? positionId = null,
        string? content = null,
        string? deepLink = null,
        decimal? price = null,
        string? levelType = null,
        string? notificationType = null,
        CancellationToken ct = default);

    /// <summary>Checks whether Redis is currently reachable.</summary>
    bool IsConnected { get; }
}
