namespace SignalStack.Worker.Push;

/// <summary>
/// DI registration for push event publishing services.
/// REQ-NFR-013: push events generated by background workers reach
/// connected portal instances via Redis pub/sub.
/// </summary>
public static class PushExtensions
{
    public static IServiceCollection AddPushEventPublisher(this IServiceCollection services)
    {
        ArgumentNullException.ThrowIfNull(services);

        services.AddSingleton<IPushEventPublisher, RedisPushEventPublisher>();

        return services;
    }
}
